### ISSUE TITLE
Plan of attack

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControlInstaller#1]
# Service Control Installer

See https://github.com/Particular/Housekeeping/issues/267

Following on from a discussion between @distantcam @simoncropp @johnsimons and @gbiellem this is what we are going to prototype for the the new SC installer

The install will be a two stage install.

In the first stage a self extracting exe (probably AdvancedInstaller) will be

  - Unpack all of the components packages to a location on disk (probably somewhere in C:\ProgramData) 
  - Register a config.exe with the startmenu
  - Launch the config.exe

The config.exe is a WPF app which shows the list of currently installed servicecontrol instances and their versions
The config.exe will allow the addition, reconfiguration, upgrade or deletion of an instance.
The config.exe UI provides the following:
  
  - Unpacking the chosen modules to the install directory
  - Choice of URL and Port Number
  - Audit Forwarding On/Off 
  - Transport choice (MSMQ, MSSQL, Azure ServiceBus, AzureStorage Queues, RabbitMQ).
  - Registering the service ( choice of credentials or system account )
  - Registering the URLACL 
  - Optional Install of perf counters (https://github.com/Particular/ServiceControl/issues/418 )
  - Set Service Start Dependancies i.e If MSMQ is chosen transport SC service should depend on it (https://github.com/Particular/ServiceControl/issues/439))

What we will determined:
- Are component modules nugets or a custom format with a manifest?
- As SC becomes more modular, module options will drive the availabe UI choices so do modules provide their own setup called by config.exe or is config.exe updated every time a module is added/changed/removed?
- Should the location of the stage 1 unpack be version specific so we can side by side two versions and still manage them?
- Do silent installs still make sense in this model? If so how are we going to do this?
- How to handle upgrades from current release?

Additional changes from current model 
- App.config will be the sole source of config for an instance - no common registry settings with the except for NSB license
- Instances need to be registered in central place (or do we trawl the services key in the registry?)
- Assume all installation code has been removed from ServiceControl.exe
- An app.config will always be provided (advanced setting populated with defaults and commented)

**Comment by gbiellem** [comment]
I'm closing this issue - any POA conversation will continue in https://github.com/Particular/PlatformDevelopment/issues/179
