### ISSUE TITLE
Edit SC Instance

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceControlInstaller#13]
The UI aspect of editing the details of an instance is done.

### Plan of Attack

- [x]  Create Edit Screen
- [x] Validate Inputs https://github.com/Particular/ServiceControlInstaller/issues/21

- [x] Stop the service if it's running
- [x] Edit the instance
- [x] Start the service again

This also needs to be hooked up to the progress display.

**Comment by petersgiles** [comment]
I'll take this

**Comment by petersgiles** [comment]
@distantcam @gbiellem Is this satisfactory?

**Comment by gbiellem** [comment]
@petersgiles  

I see a :bug: or two

- Description is wired up to instance name not the service descriptuon
- NRE throw by the audit forwarding radio button control when I reentered the edit screen  after changing some stuff. The previouc changes applied ok and service started 
- After editing logpath the main view still showed old info.  Underlying config was correct

**Comment by petersgiles** [comment]
@distantcam I think the refresh isn't working thus the 3rd :bug: @gbiellem mentioned.

**Comment by gbiellem** [comment]
Description wired up so this is now done
