### ISSUE TITLE
Upgrade SC instance execution

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceControlInstaller#15]
Task-force: @petersgiles @gbiellem @distantcam 

Upgrading an instance needs to
- [x] stop the instance (if it's running)
- [x] upgrade the binaries
- [x] start the instance (if it was running before)

And this needs to show progress

**Comment by distantcam** [comment]
![11c prompt stop instance on upgrade](https://cloud.githubusercontent.com/assets/1298847/9078318/d23b3040-3b6e-11e5-9449-30c10d303af3.png)

**Comment by petersgiles** [comment]
this is done, closing
