### ISSUE TITLE
Edit and Save as unattended config file

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceControlInstaller#16]
There's currently a button to save the config of an instance so that config can be used in an unattended install.

The idea is to open the AddInstance screen in edit mode, and then save the output instead of editing the instance.

**Comment by gbiellem** [comment]
After discussion with @distantcam we decided to pull out of the UI.
We are doing this because:

- We already have this capability to create unattended files via the PowerShell module
- Modelling an unattended install on an already running instance is an real edge case.
