### ISSUE TITLE
New SQL Transport introduces configuration complexity

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControlInstaller#17]
The new SQL transport release introduces new complexity with regard to connection strings etc,  We 
need to look at how we can address this in the UI and config logic.

**Comment by gbiellem** [comment]
@mauroservienti  We also had the a similiar idea but viewed it as something we'd look at after the first release.   

One thing I do need from you is some extra info regarding the MSSQL transport & SC.  
it wasn't clear to me if the mapping config was all that was required or I do I need to add the DLLs that contain the types mentioned in the mappings to the ServiceControl directory?

**Comment by mauroservienti** [comment]
@gbiellem sorry for the late reply.

> We also had the a similiar idea but viewed it as something we'd look at after the first release. 

cool :smile: 

> it wasn't clear to me if the mapping config was all that was required or I do I need to add the DLLs that contain the types mentioned in the mappings to the ServiceControl directory? 

mapping config is all what is needed. So SC needs to have:

* Transport assemblies
* Mapping config

Message types are not required because SC never tries to de-serialize the raw message into its concrete type (AFAIK).

**Comment by gbiellem** [comment]
@mauroservienti   Thanks for getting back to me. 

> Message types are not required because SC never tries to de-serialize the raw message into its concrete type

:tada:  Awesome - I didn't want to have to worry about custom DLLs when doing upgrades so that is great news

**Comment by gbiellem** [comment]
Closing this as there is no action to take
