### ISSUE TITLE
Validation Rules and Defaults

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControlInstaller#21]
@distantcam  @petersgiles  Please review:
### Installer Module

Errors should not be logged, should only get exceptions
No Logic to directly support the UI should be present in the installer module.

### Global Rules

These rules will be enforced in the installer module as exceptions.
Where practicable they will be caught as screen validations before executing actions in the installer.

### Installer Engine Validations
- [x] Install Path, DB Path and Logs paths should not be nested or the same
- [x] Install Path, DB Path and Logs paths must be valid path names
- [x] Install Path, DB Path and Logs must resolve to local disk not network drives or UNC paths
- [x] Paths should not be duplicated between instances
- [x] Port should available and not used by another instance
- [x] Queue names are unique across instances 
- [x] Ensure user hasn't specified the same queuename in Audit, Error, ErrorLog and AuditLoq
- [x] InstanceName should not contain whitespace chars - needs to be a valid service name
- [x] Changing Log path should use the same validation rules as add

#### Add
- [x] Non MSMQ transport types require a connection string
- [x] Hostname should default to localhost, Anything else should pop a warning since changing it exposed SC to anonymous access off the box
- [x] Paths should not be duplicated between instances
- [x] Port should default to 33333. Increment for each new instance
- [x] Port should available and not used by another instance
- [x] Ensure user hasn't specified the same queuename in Audit, Error, ErrorLog and AuditLoq
- [x] InstanceName should not contain whitespace chars - needs to be a valid service name
- [x] Queue names should not contain spaces
- [x] First instance default instance name to "Particular.ServiceControl"
- [x] Can we set default paths for Install Path, DB Path and Logs based on instance name?
- [x] The default Service Account should default to localsystem  - which it is doing but the radio button is not selected by default

#### Edit
- [x] Non MSMQ transport types require a connection string
- [x] New port isn't in use or configured as the port for another instance
- [x] Paths should not be duplicated between instances
- [x] Port should default to 33333. Increment for each new instance
- [x] Port should available and not used by another instance
- [x] Ensure user hasn't specified the same queuename in Audit, Error, ErrorLog and AuditLoq
- [x] InstanceName should not contain whitespace chars - needs to be a valid service name
- [x] Queue names should not contain spaces

**Comment by gbiellem** [comment]
Added the Service Account default - Thanks @HEskandari for pointing out I missed that one of the list :)

**Comment by petersgiles** [comment]
ok I added a bunch of things to check off and tried to capture some of the rules for fields on screen

**Comment by gbiellem** [comment]
Added queuename should not have spaces.

**Comment by petersgiles** [comment]
After some discussion we decided that queue name should just be required. This is because different transports have different naming requirements.

**Comment by petersgiles** [comment]
@gbiellem 
> Can we set default paths for Install Path, DB Path and Logs based on instance name?

Can I have an example, what would these look like if the instance name was "Particular.ServiceControl"?

**Comment by gbiellem** [comment]
@petersgiles 

How about something like this which would co-locate the db and logs in the common app data location and put the binaries in roughly the same place as now.  

```
var instanceName = "Foo"

var binFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),
	 "Particular Software", 
	instanceName);

var dbPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),
	"Particular", 
	"ServiceControl", 
  	 instancename,
	"DB");

var logPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),
	"Particular", 
	"ServiceControl", 
	instancename,
	"Logs");
```

**Comment by petersgiles** [comment]
@distantcam @HEskandari  with the way we've implemented WPF with reactive extensions how/where do I do a notify property change?

**Comment by distantcam** [comment]
@petersgiles It's done automagically with PropertyChanged.Fody. Why?

**Comment by gbiellem** [comment]
All done
