### ISSUE TITLE
Add Instance Screen

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControlInstaller#24]
Outstanding
- [x]  Add defaults as per validation rules
- [x] Audit Forwarding Check boxes dont work properly. If nothing selected and ON clicked OFF is selected
- [x] Validation notification - If add is clicked and the failed validation is off screen it's not clear that failed validation is why nothing is happening 
- [x] Hint field for Connection String needs to be clearer that it isn't an edit field

**Comment by gbiellem** [comment]
@distantcam  updated to list whats missing IMO

**Comment by petersgiles** [comment]
@gbiellem do you want me to look at this?

**Comment by distantcam** [comment]
@petersgiles If you get the validation notification done on the edit screen I can copy-n-paste it into the add screen.

**Comment by petersgiles** [comment]
@distantcam  I have added a "solution" to the add instance screen.

**Comment by gbiellem** [comment]
@petersgiles @distantcam  

There is a problem with the validation on Add Instance and the transport selection
To reproduce do this:

Choose a transport that requires a connect string. Don't enter a connection string
Change back to MSMQ
Make all fields valid 
Add button is still greyed

Looks like validation is still expecting a connection string

**Comment by petersgiles** [comment]
Validation summary is in place now. Having trouble recreating your scenario though

**Comment by petersgiles** [comment]
just included a validation that checks for path uniqueness across instances

**Comment by petersgiles** [comment]
@gbiellem is this one done now?

**Comment by distantcam** [comment]
@petersgiles There's a few edge cases in validation I'm working on now.
