### ISSUE TITLE
Installer and Config UI

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceControlInstaller#3]
Questions and notes from meeting with @distantcam @gbiellem @andreasohlund : 

### ServiceControl installer
- No options (installation only)
- All components are packaged
- Everything is copied (not installed), then installed in config later on demand, per instance options

### Config panel
- Ability to manage license (per machine, per instance?)
- Customize installation of components per instance (all live in same machine)
- How about installing certain components without having to configure them inside an instance?
- Ability to duplicate instances (and their configuration)
- Upgrades are taken care all together in a bundle
- Hotfixes, how to handle?
- Upgrades alert, how to deal with closed networks? Ask for email and notify later via email? Mention twitter?

**Comment by gbiellem** [comment]
This discussion is pretty stale now - Closing
