### ISSUE TITLE
Window doesn't come to foreground when task bar icon clicked

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControlInstaller#32]
Repo

open notepad.exe
Open our app
Click the notepad icon in taskbar and notepad becomes the foreground window
Click our app and it doesn't  

//cc: @distantcam @petersgiles

**Comment by gbiellem** [comment]
@petersgiles  or @HEskandari  do you want to take this one?

**Comment by distantcam** [comment]
Unable to reproduce.

**Comment by gbiellem** [comment]
Closing.  I can't repro it either now.
