### ISSUE TITLE
Instance Refresh doesn't appear to work correctly

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControlInstaller#36]
Refresh is broken. 
Edit an instances and changes

**Comment by gbiellem** [comment]
Still broken.
Start with no instances, Add and instance and it doesn't show up until app is restarted

**Comment by distantcam** [comment]
I'll take a look tomorrow.

**Comment by distantcam** [comment]
Fixed

**Comment by HEskandari** [comment]
@distantcam just tested, the "Edit" does not work. Simple edit an instance and change the Log path and save. When you're back at the main screen, the data shown is stale.
