### ISSUE TITLE
Instance Screen layout change - hostname and Transport name

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControlInstaller#41]
Slight layout tweak required, If the hostname is a fully qualified DNS name it can run into the Transport name

**Comment by petersgiles** [comment]
@gbiellem this is on the first screen with all the instances. Do you think we should redesign the whole thing or truncate the hostname? ...or something else maybe?

I'm currently reading my UI books to work out a better way :8ball:

**Comment by gbiellem** [comment]
<img width="564" alt="layout" src="https://cloud.githubusercontent.com/assets/2351700/9347524/1bc58af8-466e-11e5-8f4b-e8ef1e8ec6c9.PNG">

So this shows the problem.  I think just moving the hostname field further to the left would fix the majority of users.  Seems to be a lot ot space between the version and hostname.  //cc @sergioc

**Comment by petersgiles** [comment]
![capture](https://cloud.githubusercontent.com/assets/1644481/9349676/825e3fd0-468c-11e5-8a99-35b07b30f18f.PNG)

How's that

**Comment by gbiellem** [comment]
:+1:

**Comment by distantcam** [comment]
:-1: This looks :hankey: when there's an updated version.

![image](https://cloud.githubusercontent.com/assets/1298847/9351703/520f2d42-468e-11e5-82ca-0256526faaa8.png)

**Comment by sergioc** [comment]
How about using the following layout:

![screenshot 2015-08-19 10 05 19](https://cloud.githubusercontent.com/assets/493451/9352540/fc7d3ccc-4659-11e5-9bb4-ba9aa1152276.png)

I.e. show "SC version" and "Host" in one line, bring "transport" to a second line (and possibly think of another instance property to add to the second line). 

Paths can remain each on its own line like we have now.
