### ISSUE TITLE
Username field not updating on Edit screen

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControlInstaller#43]
When an instance is running as a user account and it is switched bay to localsystem the username field still says the old account name

**Comment by distantcam** [comment]
I might have introduced that as part of making a common vm for add and edit.

**Comment by gbiellem** [comment]
Also when editing the progess dialog says "adding instance" - I'm assuming that was also from that change

**Comment by distantcam** [comment]
Possibly. :D

**Comment by distantcam** [comment]
@gbiellem I can't repro this. Is this the right steps?

- Create a new instance with a user account
- Check the service is running as that user
- Edit the instance to the system account
- Check the service is running as the system account

**Comment by gbiellem** [comment]
retested and It's working :tada:
