### ISSUE TITLE
Inconsistent usage of confirmation that service will stopped dialog

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControlInstaller#51]
When upgrading a stop service confirmation dialog is shown .  
When modifying the settings it isn't shown 

Also should it be shown when we hit the stop button?

//cc @distantcam  @petersgiles

**Comment by distantcam** [comment]
> Also should it be shown when we hit the stop button?

No. It's only warning for situations when it's unclear that the action will cause the service to be stopped.

**Comment by gbiellem** [comment]
:+1: Makes sense
