### ISSUE TITLE
ReportCard view doesn't wrap long messages

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControlInstaller#52]
Message Text is not wrapping

![capture](https://cloud.githubusercontent.com/assets/2351700/9402148/da076158-481c-11e5-9a51-85b806e3a2cc.png)

**Comment by petersgiles** [comment]
![capture](https://cloud.githubusercontent.com/assets/1644481/9402561/066eeba8-4822-11e5-8b77-adf286235ad9.PNG)

Fixed now
