### ISSUE TITLE
Using Tab to get to the Audit forwarding radio buttons causes a unhandled exception

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControlInstaller#53]
Repro:

- Click on add new instance
- Start pressing tab to move between fields. 
- Crashes when you get to the audit forwarding radio buttons 

Exception message:  "'offBullet' name cannot be found in the name scope of 'System.Windows.Controls.Grid'."

//cc @distantcam @petersgiles

**Comment by petersgiles** [comment]
This occurs on both the Add and Edit Screens.

More info {"Modal frame exception. Check inner exception for details."}
Inner Exception {"'offBullet' name cannot be found in the name scope of 'System.Windows.Controls.Grid'."}

offBullet is in FormCheckBox Style in Generic.xaml

So anyway I thought I'd go through and make things like the logo IsTabStop="False" and then I figured lets see if it still blows up when I do this:

`FormCheckBox IsTabStop="False" 

and lo it was a good thought and the tabbing did no longer blow the UI up!

**Comment by petersgiles** [comment]
fixed in https://github.com/Particular/ServiceControlInstaller/commit/2d97f94a5e7d2d579f2912efa31b44708af9ce6b
